export const SET_LATITUDE = "SET_LATITUDE"

export const SET_LONGITUDE = "SET_LONGITUDE"

export const SET_GEOHASH = "SET_GEOHASH"

export const SET_SHOPLIST = "SET_SHOPLIST"

export const SET_BUYFOODLIST = "SET_BUYFOODLIST"

export const INIT_SET_BUYFOODLIST = "INIT_SET_BUYFOODLIST"

export const CLEAR_BUYFOODLIST = "CLEAR_BUYFOODLIST"