export const SET_LATITUDE = "SET_LATITUDE"

export const SET_LONGITUDE = "SET_LONGITUDE"

export const SET_GEOHASH = "SET_GEOHASH"

export const SET_SHOPLIST = "SET_SHOPLIST"

export const SET_BUYFOODLIST = "SET_BUYFOODLIST"

export const INIT_SET_BUYFOODLIST = "INIT_SET_BUYFOODLIST"

export const CLEAR_BUYFOODLIST = "CLEAR_BUYFOODLIST"

export const SET_CARTTIME = "SET_CARTTIME"

export const SET_SHOPDETAIL = "SET_SHOPDETAIL"

export const SET_USERINFO = "SET_USERINFO"

export const RECODE_USERINFO = "RECODE_USERINFO"